### ISSUE TITLE
Clock flickers

### ISSUE THREAD

**Issue by Reyhn3** [Oughie/clock-rs#2] opened 2024-08-06 13:04 UTC
Running the basic command `clock-rs` will display the clock, but it flickers twice a second. If increasing the interval to e.g.

```
clock-rs --interval 100
```

the rendering will flicker ten times per second.

I've had the same issue in my own C#-applications, and that has been because I have tried filling the entire screen with characters. The solution (in Windows) is to use [alternate screen buffer](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#alternate-screen-buffer). This is using virtual terminal escape codes, so this solution should work here as well. I'm not an expert in this, but it might be a hint to where to start looking.

**Details:**
OS: Windows 10
Terminal: Windows Terminal
Console size: 120 x 31
clock-rs: Cloned 2024-08-06
rustc: 1.80.0 (051478957 2024-07-21)

**Comment by Oughie** [comment] 2024-08-07 08:25
Thank you for opening an issue 😁 

I've created a new release in which the previous screen won't be cleared after `clock-rs` has finished.
Since I'm using the alternate screen mode for that, your issue could be resolved in the new update.

Are you able to reproduce this in verson 0.1.2? You can use `cargo install clock-rs --force` to update.

**Comment by Reyhn3** [comment] 2024-08-07 12:43
I appreciated the fast response!

I need some help, though, with verifying this. I'm completely new to Rust, and I can't get the new version to run even though everything looks alright.

I've pulled the latest main branch:

```powershell
❯ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

I can see that I have the changes you pushed a few hours ago.
And then I build:

```powershell
❯ cargo install clock-rs --force
    Updating crates.io index
  Installing clock-rs v0.1.2
...
   Compiling clock-rs v0.1.2
    Finished `release` profile [optimized] target(s) in 1m 33s
   Replacing C:\Users\reyhn\.cargo\bin\clock-rs.exe
    Replaced package `clock-rs v0.1.1` with `clock-rs v0.1.2` (executable `clock-rs.exe`)
```

But when I run the clock, it's still the old version number, and the time is still flickering:

```powershell
❯ C:\Users\reyhn\.cargo\bin\clock-rs.exe --version
clock-rs v0.1.0, (C) 2024 Oughie
```

I'm guessing that either your fix didn't work and the build didn't update the version number, which seems unlikely, or something has gone wrong during the compilation. Do you have any idea?

(Also, I can see that the binary reports version `0.1.0`, but the previous version that was replaced with the `cargo install` command was version `0.1.1`, which is odd. I am certain that I checked out this repo for the very first time yesterday 2024-08-06, installed rust and executed `cargo install` yesterday, so it should have been version `0.1.1` since that commit is from 2024-07-27. I don't know if this is a clue to what's going on...)

Also, I noticed a few other things as well:

* The binary `clock-rs.exe` does not have the version number embedded in its file properties
* There's a spelling error in [Cargo.toml](https://github.com/Oughie/clock-rs/blob/main/Cargo.toml#L7)
* This repository has not tagged the commit with the version number - it would be easier to find if the commit "Version 0.1.1" also had a tag e.g. "v0.1.1" since there are no releases in this repository

I'm sorry I couldn't just confirm this fix, but right now I'm stuck due too little experience with rust. ):

**Comment by Oughie** [comment] 2024-08-07 13:54
My fault, just some typos I made!

**Comment by Oughie** [comment] 2024-08-07 14:21
My fault, just some typos I made!
In my code, I had forgotten to update `clock-rs v0.1.0, (C) 2024 Oughie` to `clock-rs v0.1.2, (C) 2024 Oughie`. Also, I now got rid of the horrific typo in `Cargo.toml`.

You did everything right, it's just the typos I accidentally made. Since you installed the new version of the project which is still flickering, using the alternate screen seemed to not help resolve this issue.
I'm on Linux using the kitty terminal where it does work fine (on Alacritty as well), so I sadly cannot test it in the Windows Terminal since I'm not on Windows! For now, I'll push the fixes for the typos (v0.1.201) and I will try to fix this issue, but I can't promise that I will be able to!

**Comment by Reyhn3** [comment] 2024-08-08 10:03
That explains a lot (:

Unfortunately, I cannot say that the fix solved the flickering. ):

I have not tried `tty-clock` but I have tried `clock-rs` version `0.1.201` and it still flickers on Windows:

* Windows Terminal (v1.20.11781.0)
* Alacritty (v0.13.2)
* Hyper (v3.4.1)
* Tabby (v1.0.208)

I've tried these terminals in a fresh Windows 10 VM with the same 120 x 30 size, and they all flicker.

However, most surprisingly, the standard **Windows Command Prompt** is the most stable one! It only starts to flicker when the terminal is resized. Maybe this is a clue, or another bug (that buffer resizes are not handled)?

Alacritty is the second most stable, because it flickers more occasionally, whereas the other terminals flicker on each refresh. Also, in Alacritty, the cursor is visible.

**Comment by Reyhn3** [comment] 2024-08-08 10:17
I just created issue #3 for a different problem.
I have tested both of these issues on a Windows 10 laptop and in a virtual Windows 10 running inside that laptop. The VM gives me more confidence in that it is not only my environment, but it would be helpful to have another Windows-user corroborate my findings. As of now, I couldn't say if it is related to Windows specifically or not. Currently, I'm not able to test on any other machine or OS (and won't be for some time).

**Comment by Oughie** [comment] 2024-08-25 08:16
@Reyhn3 I've just published `clock-rs v0.1.204`. Apart from clean-ups, I changed it to only clear the screen on terminal resize, meaning your issue could be resolved. Could you upgrade `clock-rs` using `$ cargo install clock-rs --force` and see if the issue still persists? Thank you 😄

**Comment by Oughie** [comment] 2024-09-16 16:37
Closing this issue due to inactivity.

**Closed by Oughie** 2024-09-16 16:37 UTC
Labels: bug

**Comment by Reyhn3** [comment] 2024-09-26 08:13
Sorry for the delayed response, but I can confirm that the clock no longer flickers (v0.1.210)!
Thank you!

**Comment by Oughie** [comment] 2024-09-26 18:58
Glad to hear ^^.
